---
source_directory: "spec/infra/harness"
state_file: "%{hiera('project_directory')}/state/harness.tfstate"
vars:
  region: "%{hiera('region')}"

  bucket_name: "infrablocks-encrypted-%{hiera('deployment_identifier')}"

  acl: "%{hiera('acl')}"

  include_source_policy_json: "%{hiera('include_source_policy_json')}"

  mfa_delete: "%{hiera('mfa_delete')}"

  allow_destroy_when_objects_present: "%{hiera('allow_destroy_when_objects_present')}"
